(function (teslo) {
  teslo.prelude = {
    source: [
"(def defm (macro (name . signatures) `(def ~name (macro ~@signatures))))",
"",
"(defm defn (name . signatures) `(def ~name (fn ~@signatures)))",
"",
"(defm deft (tname . params) `(def ~tname (create-type (name '~tname) ~@params)))",
"",
"(defm do (. x) `((fn (. x) (last x)) ~@x))",
"",
"(defn identity (x) x)",
"",
"(defm -> (v f)      `(~f ~v)",
"         (v f . fs) `(-> (~f ~v) ~@fs))",
"",
"(defn inc (x) (+ x 1))",
"",
"(defn dec (x) (- x 1))",
"",
"(defn string ((k : Keyword)) (+ \":\" (name k))",
"             ((s : Symbol))  (name s)",
"             ((s : String))  (+ \"\\\"\" s \"\\\"\")",
"             ((n : Number))  (+ n \"\")",
"             ((l : List))    (+ \"(\" (join (map string l) \" \") \")\")",
"             ((a : Array))   (+ \"(\" (join (map string a) \" \") \")\")",
"             (x)             (string* x string))",
"",
"(defn print (x) (log* (string x)))",
"",
"",
";; Lists",
"",
"(deft List ()",
"           (head tail))",
"",
"(def nil (List))",
"",
"",
";; Sequences",
"",
"(defn first ((a : Array)) (array-first* a)",
"            ((List h t)) h)",
"",
"(defn rest ((a : Array)) (array-rest* a)",
"           ((List h t))  t",
"           ((List))      nil)",
"",
"(defn last ((a : Array))     (array-last* a)",
"           ((List h (List))) h",
"           ((List h t))      (last t))",
"",
"(defn length ((a : Array)) (array-length* a)",
"             ((List h t))  (+ 1 (length t))",
"             ((List))      0)",
"",
"(defn map (f (List h t))  (List (f h) (map f t))",
"          (f (List))      nil",
"          (f (a : Array)) (match (array-length* a)",
"                                 0 nil",
"                                 _ (let (h (first a)",
"                                         t (rest a))",
"                                     (List (f h) (map f t)))))",
"",
"(defn reduce (f a (List h t)) (reduce f (f a h) t)",
"             (f a (List))     a)",
"",
"(defn join ((List h t) sep) (reduce (fn (a h*) (+ a sep h*)) h t)",
"           ((List) sep)     \"\")",
""
].join('\n'),
    ops: [
["value",{"name":"defm","!meta":{"type":"Symbol"}}],
["value",[{"name":"macro","!meta":{"type":"Symbol"}},[{"name":"name","!meta":{"type":"Symbol"}},{"name":".","!meta":{"type":"Symbol"}},{"name":"signatures","!meta":{"type":"Symbol"}}],[{"name":"syntax-quote","!meta":{"type":"Symbol"}},[{"name":"def","!meta":{"type":"Symbol"}},[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"name","!meta":{"type":"Symbol"}}],[{"name":"macro","!meta":{"type":"Symbol"}},[{"name":"unquote-splice","!meta":{"type":"Symbol"}},{"name":"signatures","!meta":{"type":"Symbol"}}]]]]]],
["lookup","def"],
["invoke",2],
["value",{"name":"defn","!meta":{"type":"Symbol"}}],
["value",[{"name":"macro","!meta":{"type":"Symbol"}},[{"name":"name","!meta":{"type":"Symbol"}},{"name":".","!meta":{"type":"Symbol"}},{"name":"signatures","!meta":{"type":"Symbol"}}],[{"name":"syntax-quote","!meta":{"type":"Symbol"}},[{"name":"def","!meta":{"type":"Symbol"}},[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"name","!meta":{"type":"Symbol"}}],[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"unquote-splice","!meta":{"type":"Symbol"}},{"name":"signatures","!meta":{"type":"Symbol"}}]]]]]],
["lookup","def"],
["invoke",2],
["value",{"name":"deft","!meta":{"type":"Symbol"}}],
["value",[{"name":"macro","!meta":{"type":"Symbol"}},[{"name":"tname","!meta":{"type":"Symbol"}},{"name":".","!meta":{"type":"Symbol"}},{"name":"params","!meta":{"type":"Symbol"}}],[{"name":"syntax-quote","!meta":{"type":"Symbol"}},[{"name":"def","!meta":{"type":"Symbol"}},[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"tname","!meta":{"type":"Symbol"}}],[{"name":"create-type","!meta":{"type":"Symbol"}},[{"name":"name","!meta":{"type":"Symbol"}},[{"name":"quote","!meta":{"type":"Symbol"}},[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"tname","!meta":{"type":"Symbol"}}]]],[{"name":"unquote-splice","!meta":{"type":"Symbol"}},{"name":"params","!meta":{"type":"Symbol"}}]]]]]],
["lookup","def"],
["invoke",2],
["value",{"name":"do","!meta":{"type":"Symbol"}}],
["value",[{"name":"macro","!meta":{"type":"Symbol"}},[{"name":".","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}}],[{"name":"syntax-quote","!meta":{"type":"Symbol"}},[[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":".","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}}],[{"name":"last","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}}]],[{"name":"unquote-splice","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}}]]]]],
["lookup","def"],
["invoke",2],
["value",{"name":"identity","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"x","!meta":{"type":"Symbol"}}],{"name":"x","!meta":{"type":"Symbol"}}]],
["lookup","def"],
["invoke",2],
["value",{"name":"->","!meta":{"type":"Symbol"}}],
["value",[{"name":"macro","!meta":{"type":"Symbol"}},[{"name":"v","!meta":{"type":"Symbol"}},{"name":"f","!meta":{"type":"Symbol"}}],[{"name":"syntax-quote","!meta":{"type":"Symbol"}},[[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"f","!meta":{"type":"Symbol"}}],[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"v","!meta":{"type":"Symbol"}}]]],[{"name":"v","!meta":{"type":"Symbol"}},{"name":"f","!meta":{"type":"Symbol"}},{"name":".","!meta":{"type":"Symbol"}},{"name":"fs","!meta":{"type":"Symbol"}}],[{"name":"syntax-quote","!meta":{"type":"Symbol"}},[{"name":"->","!meta":{"type":"Symbol"}},[[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"f","!meta":{"type":"Symbol"}}],[{"name":"unquote","!meta":{"type":"Symbol"}},{"name":"v","!meta":{"type":"Symbol"}}]],[{"name":"unquote-splice","!meta":{"type":"Symbol"}},{"name":"fs","!meta":{"type":"Symbol"}}]]]]],
["lookup","def"],
["invoke",2],
["value",{"name":"inc","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"x","!meta":{"type":"Symbol"}}],[{"name":"+","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}},1]]],
["lookup","def"],
["invoke",2],
["value",{"name":"dec","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"x","!meta":{"type":"Symbol"}}],[{"name":"-","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}},1]]],
["lookup","def"],
["invoke",2],
["value",{"name":"string","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[[{"name":"k","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Keyword","!meta":{"type":"Symbol"}}]],[{"name":"+","!meta":{"type":"Symbol"}},":",[{"name":"name","!meta":{"type":"Symbol"}},{"name":"k","!meta":{"type":"Symbol"}}]],[[{"name":"s","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Symbol","!meta":{"type":"Symbol"}}]],[{"name":"name","!meta":{"type":"Symbol"}},{"name":"s","!meta":{"type":"Symbol"}}],[[{"name":"s","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"String","!meta":{"type":"Symbol"}}]],[{"name":"+","!meta":{"type":"Symbol"}},"\"",{"name":"s","!meta":{"type":"Symbol"}},"\""],[[{"name":"n","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Number","!meta":{"type":"Symbol"}}]],[{"name":"+","!meta":{"type":"Symbol"}},{"name":"n","!meta":{"type":"Symbol"}},""],[[{"name":"l","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"List","!meta":{"type":"Symbol"}}]],[{"name":"+","!meta":{"type":"Symbol"}},"(",[{"name":"join","!meta":{"type":"Symbol"}},[{"name":"map","!meta":{"type":"Symbol"}},{"name":"string","!meta":{"type":"Symbol"}},{"name":"l","!meta":{"type":"Symbol"}}]," "],")"],[[{"name":"a","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Array","!meta":{"type":"Symbol"}}]],[{"name":"+","!meta":{"type":"Symbol"}},"(",[{"name":"join","!meta":{"type":"Symbol"}},[{"name":"map","!meta":{"type":"Symbol"}},{"name":"string","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}]," "],")"],[{"name":"x","!meta":{"type":"Symbol"}}],[{"name":"string*","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}},{"name":"string","!meta":{"type":"Symbol"}}]]],
["lookup","def"],
["invoke",2],
["value",{"name":"print","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"x","!meta":{"type":"Symbol"}}],[{"name":"log*","!meta":{"type":"Symbol"}},[{"name":"string","!meta":{"type":"Symbol"}},{"name":"x","!meta":{"type":"Symbol"}}]]]],
["lookup","def"],
["invoke",2],
["value",{"name":"List","!meta":{"type":"Symbol"}}],
["value",[{"name":"create-type","!meta":{"type":"Symbol"}},[{"name":"name","!meta":{"type":"Symbol"}},[{"name":"quote","!meta":{"type":"Symbol"}},{"name":"List","!meta":{"type":"Symbol"}}]],[],[{"name":"head","!meta":{"type":"Symbol"}},{"name":"tail","!meta":{"type":"Symbol"}}]]],
["lookup","def"],
["invoke",2],
["value",{"name":"nil","!meta":{"type":"Symbol"}}],
["value",[{"name":"List","!meta":{"type":"Symbol"}}]],
["lookup","def"],
["invoke",2],
["value",{"name":"first","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[[{"name":"a","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Array","!meta":{"type":"Symbol"}}]],[{"name":"array-first*","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}],[[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],{"name":"h","!meta":{"type":"Symbol"}}]],
["lookup","def"],
["invoke",2],
["value",{"name":"rest","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[[{"name":"a","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Array","!meta":{"type":"Symbol"}}]],[{"name":"array-rest*","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}],[[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],{"name":"t","!meta":{"type":"Symbol"}},[[{"name":"List","!meta":{"type":"Symbol"}}]],{"name":"nil","!meta":{"type":"Symbol"}}]],
["lookup","def"],
["invoke",2],
["value",{"name":"last","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[[{"name":"a","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Array","!meta":{"type":"Symbol"}}]],[{"name":"array-last*","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}],[[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},[{"name":"List","!meta":{"type":"Symbol"}}]]],{"name":"h","!meta":{"type":"Symbol"}},[[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],[{"name":"last","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]]],
["lookup","def"],
["invoke",2],
["value",{"name":"length","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[[{"name":"a","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Array","!meta":{"type":"Symbol"}}]],[{"name":"array-length*","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}],[[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],[{"name":"+","!meta":{"type":"Symbol"}},1,[{"name":"length","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],[[{"name":"List","!meta":{"type":"Symbol"}}]],0]],
["lookup","def"],
["invoke",2],
["value",{"name":"map","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"f","!meta":{"type":"Symbol"}},[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],[{"name":"List","!meta":{"type":"Symbol"}},[{"name":"f","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}}],[{"name":"map","!meta":{"type":"Symbol"}},{"name":"f","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],[{"name":"f","!meta":{"type":"Symbol"}},[{"name":"List","!meta":{"type":"Symbol"}}]],{"name":"nil","!meta":{"type":"Symbol"}},[{"name":"f","!meta":{"type":"Symbol"}},[{"name":"a","!meta":{"type":"Symbol"}},{"name":":","!meta":{"type":"Symbol"}},{"name":"Array","!meta":{"type":"Symbol"}}]],[[{"name":"fn","!meta":{"type":"Symbol"}},[0],{"name":"nil","!meta":{"type":"Symbol"}},[{"name":"_","!meta":{"type":"Symbol"}}],[[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}],[{"name":"List","!meta":{"type":"Symbol"}},[{"name":"f","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}}],[{"name":"map","!meta":{"type":"Symbol"}},{"name":"f","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]]],[{"name":"first","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}],[{"name":"rest","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}]]],[{"name":"array-length*","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}}]]]],
["lookup","def"],
["invoke",2],
["value",{"name":"reduce","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"f","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}},[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}]],[{"name":"reduce","!meta":{"type":"Symbol"}},{"name":"f","!meta":{"type":"Symbol"}},[{"name":"f","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}}],{"name":"t","!meta":{"type":"Symbol"}}],[{"name":"f","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}},[{"name":"List","!meta":{"type":"Symbol"}}]],{"name":"a","!meta":{"type":"Symbol"}}]],
["lookup","def"],
["invoke",2],
["value",{"name":"join","!meta":{"type":"Symbol"}}],
["value",[{"name":"fn","!meta":{"type":"Symbol"}},[[{"name":"List","!meta":{"type":"Symbol"}},{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}],{"name":"sep","!meta":{"type":"Symbol"}}],[{"name":"reduce","!meta":{"type":"Symbol"}},[{"name":"fn","!meta":{"type":"Symbol"}},[{"name":"a","!meta":{"type":"Symbol"}},{"name":"h*","!meta":{"type":"Symbol"}}],[{"name":"+","!meta":{"type":"Symbol"}},{"name":"a","!meta":{"type":"Symbol"}},{"name":"sep","!meta":{"type":"Symbol"}},{"name":"h*","!meta":{"type":"Symbol"}}]],{"name":"h","!meta":{"type":"Symbol"}},{"name":"t","!meta":{"type":"Symbol"}}],[[{"name":"List","!meta":{"type":"Symbol"}}],{"name":"sep","!meta":{"type":"Symbol"}}],""]],
["lookup","def"],
["invoke",2]
]
  };
})(this.teslo || require('../'));